# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.generic import RedirectView


urlpatterns = patterns(
    'main.views',
    url(
        regex=r'^$',
        view='load_story_list_page'
    ),
    url(
        regex=r'^login/$',
        view='user_login'
    ),
    url(
        regex=r'^login/oauth/$',
        view='user_login_with_oauth'
    ),
    url(
        regex=r'^logout/$',
        view='user_logout'
    ),
    url(
        regex=r'^user/create/$',
        view='user_signup'
    ),
    url(
        regex=r'^user/email/$',
        view='load_update_user_email_page'
    ),
    url(
        regex=r'^user/email/update/$',
        view='update_user_email'
    ),
    url(
        regex=r'^user/email/verification/$',
        view='send_verification_email'
    ),
    url(
        regex=r'^user/email/verification/(?P<secret_code>\w+)/$',
        view='verify_user_email'
    ),
    url(
        regex=r'^user/nickname/$',
        view='load_update_user_nickname_page'
    ),
    url(
        regex=r'^user/nickname/update/$',
        view='update_user_nickname'
    ),
    url(
        regex=r'^user/language/$',
        view='load_update_user_language_page'
    ),
    url(
        regex=r'^user/language/update/$',
        view='update_user_language'
    ),
    url(
        regex=r'^user/password/$',
        view='load_update_user_password_page'
    ),
    url(
        regex=r'^user/password/update/$',
        view='update_user_password'
    ),
    url(
        regex=r'^user/password/forgot/$',
        view='load_forgot_password_page'
    ),
    url(
        regex=r'^user/password/forgot/send/$',
        view='send_secret_code_with_email'
    ),
    url(
        regex=r'^user/password/temporary/(?P<secret_code>\w+)/$',
        view='issue_temporary_password'
    ),
    url(
        regex=r'^user/notification/update/$',
        view='update_notification_setting_of_user'
    ),
    url(
        regex=r'^user/dropout/$',
        view='load_dropout_user_page'
    ),
    url(
        regex=r'^user/delete/$',
        view='dropout_user'
    ),
    url(
        regex=r'^user/deactivate/$',
        view='deactivate_user'
    ),
    url(
        regex=r'^user/stories/$',
        view='load_user_contributed_story_list_page'
    ),
    url(
        regex=r'^user/stories/(?P<pagination>\d+)/$',
        view='get_user_contributed_stories'
    ),
    url(
        regex=r'^user/comments/$',
        view='load_user_wrote_comment_list_page'
    ),
    url(
        regex=r'^user/comments/(?P<pagination>\d+)/$',
        view='get_user_wrote_comments'
    ),
    url(
        regex=r'^user/replies/$',
        view='load_user_wrote_reply_list_page'
    ),
    url(
        regex=r'^user/replies/(?P<pagination>\d+)/$',
        view='get_user_wrote_replies'
    ),
    url(
        regex=r'^user/reward/$',
        view='give_reward_point_to_informant'
    ),
    url(
        regex=r'^users/score/$',
        view='get_score_of_users'
    ),
    url(
        regex=r'^identity/delete/facebook/$',
        view='dropout_user_signed_up_with_facebook'
    ),
    url(
        regex=r'^story/new/$',
        view='load_new_story_page'
    ),
    url(
        regex=r'^story/create/$',
        view='create_story'
    ),
    url(
        regex=r'^story/favorite/$',
        view='load_user_favorite_story_list_page'
    ),
    url(
        regex=r'^story/favorite/(?P<pagination>\d+)/$',
        view='get_user_favorite_stories'
    ),
    url(
        regex=r'^story/favorite/add/(?P<story_id>\d+)/$',
        view='add_story_to_favorite_story_list'
    ),
    url(
        regex=r'^story/favorite/remove/whole/$',
        view='remove_whole_story_from_favorite_story_list'
    ),
    url(
        regex=r'^story/favorite/remove/(?P<story_id>\d+)/$',
        view='remove_story_from_favorite_story_list'
    ),
    url(
        regex=r'^story/read/$',
        view='load_read_story_list_page'
    ),
    url(
        regex=r'^story/(?P<story_id>\d+)/$',
        view='load_story_detail_page'
    ),
    url(
        regex=r'^story/(?P<story_id>\d+)/$',
        view='load_story_detail_page'
    ),
    url(
        regex=r'^story/(?P<story_id>\d+)/close/$',
        view='close_story'
    ),
    url(
        regex=r'^story/(?P<story_id>\d+)/delete/$',
        view='delete_story'
    ),
    url(
        regex=r'^story/(?P<story_id>\d+)/contributor/check/$',
        view='check_whether_user_contributed_story_or_not'
    ),
    url(
        regex=r'^story/(?P<story_id>\d+)/cache/update/$',
        view='update_story_cache'
    ),
    url(
        regex=r'^stories/$',
        view='get_stories_with_options'
    ),
    url(
        regex=r'^stories/list/$',
        view='get_stories_from_the_story_id_list'
    ),
    url(
        regex=r'^stories/recommended/$',
        view='get_recommended_stories'
    ),
    url(
        regex=r'^stories/search/title/(?P<title>[\w ]+)/$',
        view='load_story_list_page_searched_by_title'
    ),
    url(
        regex=r'^stories/search/title/(?P<title>[\w ]+)/(?P<pagination>\d+)/$',
        view='get_stories_searched_by_title'
    ),
    url(
        regex=r'^stories/search/tag/(?P<tag>[\w ]+)/$',
        view='load_story_list_page_searched_by_tag'
    ),
    url(
        regex=r'^stories/search/tag/(?P<tag>[\w ]+)/(?P<pagination>\d+)/$',
        view='get_stories_searched_by_tag'
    ),
    url(
        regex=r'^closing_vote/create/$',
        view='create_closing_vote'
    ),
    url(
        regex=r'^closing_vote/(?P<closing_vote_id>\d+)/$',
        view='get_closing_vote'
    ),
    url(
        regex=r'^closing_vote/(?P<closing_vote_id>\d+)/agree/$',
        view='vote_agreement_to_closing_vote'
    ),
    url(
        regex=r'^closing_vote/(?P<closing_vote_id>\d+)/disagree/$',
        view='vote_disagreement_to_closing_vote'
    ),
    url(
        regex=r'^comment/create/$',
        view='create_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/$',
        view='get_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/delete/$',
        view='delete_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/firebase/$',
        view='update_firebase_db_for_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/like/$',
        view='vote_like_to_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/dislike/$',
        view='vote_dislike_to_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/report/$',
        view='report_comment'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/vote/check/$',
        view='check_whether_user_voted_to_comment_or_not'
    ),
    url(
        regex=r'^comment/(?P<comment_id>\d+)/cache/update/$',
        view='update_comment_cache'
    ),
    url(
        regex=r'^comments/$',
        view='get_comments'
    ),
    url(
        regex=r'^reply/create/$',
        view='create_reply'
    ),
    url(
        regex=r'^reply/(?P<reply_id>\d+)/$',
        view='get_reply'
    ),
    url(
        regex=r'^reply/(?P<reply_id>\d+)/delete/$',
        view='delete_reply'
    ),
    url(
        regex=r'^reply/(?P<reply_id>\d+)/report/$',
        view='report_reply'
    ),
    url(
        regex=r'^reply/(?P<reply_id>\d+)/cache/update/$',
        view='update_reply_cache'
    ),
    url(
        regex=r'^replies/$',
        view='get_replies'
    ),
    url(
        regex=r'^notifications/$',
        view='load_notification_page'
    ),
    url(
        regex=r'^notifications/(?P<pagination>\d+)/$',
        view='get_notifications'
    ),
    url(
        regex=r'^tag/$',
        view='get_tag'
    ),
    url(
        regex=r'^analytics/$',
        view='load_analytics_page'
    ),
    url(
        regex=r'^voc/$',
        view='load_voice_of_customer_page'
    ),
    url(
        regex=r'^voc/create/$',
        view='create_voice_of_customer'
    ),
    url(
        regex=r'^terms/$',
        view='load_terms_of_use_page'
    ),
    url(
        r'^service/numeric_data/$',
        view='get_numeric_data_of_service'
    ),
    url(
        r'^service/admin/$',
        view='load_custom_admin_page'
    ),
)
